[package]
name = "rust_gl"
version = "0.1.0"
authors = ["Arithmetic-Overflow <aryageza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
image = "*"
noise = "*"